particle:
  server:
    port: 8092
    cors:
      enabled: true
  application:
    name: offers
redis:
  uri: "redis://localhost:${REDIS_PORT:6379}"
consul:
  client:
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
offers:
  api:
    version: v1