particle:
    application:
        name: storefronthtml
    server:
        port: 8080
router:
    static:
        resources:
            enabled: true
            mapping: /assets/**
            paths:
                - classpath:static
petstore:
    html:
        template: /index.html
    cookie:
        name: micronautUuid
    url: http://localhost:8080
consul:
    client:
        registration:
            enabled: true
        defaultZone: '${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}'